-- 코드를 작성해주세요
SELECT fi.ID, fni.FISH_NAME, fi.LENGTH
FROM FISH_INFO AS fi
JOIN FISH_NAME_INFO AS fni
ON fi.FISH_TYPE = fni.FISH_TYPE
WHERE Fi.FISH_TYPE IN 
(
    SELECT FISH_TYPE
    FROM FISH_INFO
    GROUP BY FISH_TYPE
    HAVING LENGTH = MAX(LENGTH)
)
ORDER BY
FI.ID;